  export const triggerValueTypes: Record<TriggerValueTypeKeys, {
    name: string,
    inherits?: Array<TriggerValueTypeKeys>,
  }> = {
    "any":                {name: "Any"},

    "number":             {name: "Number",  },
    "boolean":            {name: "Boolean", },
    "vector":             {name: "Vector",  },
    "string":             {name: "String",  },
    "array":              {name: "Array",   },
    "struct":             {name: "Struct",  },

    "Input":              {name: "Input",               },
    "Player":             {name: "Player",              inherits: ["Input"]},
    "Entity":             {name: "Entity",              },
    "ObjectEntity":       {name: "Object Entity",       inherits: ["Entity", "AdvancedObject"]},
    "ControllingEntity":  {name: "Controlling Entity",  inherits: ["ObjectEntity"]},
    "Tank":               {name: "Tank",                inherits: ["ControllingEntity", "Input"]},
    "AdvancedObject":     {name: "Advanced Object",     },
    "BotTank":            {name: "Bot Tank",            inherits: ["Tank"]},
    "Boss":               {name: "Boss",                inherits: ["ControllingEntity"]},
    "Shape":              {name: "Shape",               inherits: ["ControllingEntity"]},
    "Bullet":             {name: "Bullet",              inherits: ["ObjectEntity"]},
    "CustomObjectEntity": {name: "Custom Object Entity",inherits: ["ControllingEntity"]},
    "AreaEntity":         {name: "Area Entity",         inherits: ["Entity"]},
    "MazeWall":           {name: "Maze Wall",           inherits: ["AreaEntity"]},
    "TeamBase":           {name: "Team Base",           inherits: ["AreaEntity"]},
    "CustomAreaEntity":   {name: "Custom Area Entity",  inherits: ["AreaEntity"]},
    "Barrel":             {name: "Barrel",              },
    "AutoTurret":         {name: "Auto Turret",         inherits: ["AdvancedObject", "Input"]},
    "AdvancedObjectDef":  {name: "Advanced Object Definition",  },
    "BulletDef":          {name: "Bullet Definition",   inherits: ["AdvancedObjectDef"]},
    "TankDef":            {name: "Tank Definition",     inherits: ["AdvancedObjectDef"]},
    "ShapeDef":           {name: "Shape Definition",    inherits: ["AdvancedObjectDef"]},
    "BossDef":            {name: "Boss Definition",     inherits: ["AdvancedObjectDef"]},
  }